### ISSUE TITLE
Issues loading in geqdsk files with stuff in the first line

### ISSUE THREAD

**Issue by Maxwell-Rosen** [ammarhakim/gkylzero#332]
There is an issue when loading geqdsk files. Recently, I got a new geqdsk file that I wanted to use and it was producing a funky error message. It was a big confusion, until I realized that we have to slightly modify the files by removing some words in the first line. This is what a standard geqdsk file looks like.

```c
 PLEIADES mirror_eqdsk                             0 129 257
 2.200000000e-01 1.960000000e+00 0.000000000e+00 0.000000000e+00 0.000000000e+00
 0.000000000e+00 0.000000000e+00 0.000000000e+00 3.699013406e-03 0.000000000e+00
 0.000000000e+00 0.000000000e+00 0.000000000e+00 0.000000000e+00 0.000000000e+00
 0.000000000e+00 0.000000000e+00 3.699013406e-03 0.000000000e+00 0.000000000e+00
 0.000000000e+00 0.000000000e+00 0.000000000e+00 0.000000000e+00 0.000000000e+00
 0.000000000e+00 0.000000000e+00 0.000000000e+00 0.000000000e+00 0.000000000e+00
 0.000000000e+00 0.000000000e+00 0.000000000e+00 0.000000000e+00 0.000000000e+00
 0.000000000e+00 0.000000000e+00 0.000000000e+00 0.000000000e+00 0.000000000e+00
 0.000000000e+00 0.000000000e+00 0.000000000e+00 0.000000000e+00 0.000000000e+00
 0.000000000e+00 0.000000000e+00 0.000000000e+00 0.000000000e+00 0.000000000e+00
 0.000000000e+00 0.000000000e+00 0.000000000e+00 0.000000000e+00 0.000000000e+00
 0.000000000e+00 0.000000000e+00 0.000000000e+00 0.000000000e+00 0.000000000e+00
 0.000000000e+00 0.000000000e+00 0.000000000e+00 0.000000000e+00 0.000000000e+00
 0.000000000e+00 0.000000000e+00 0.000000000e+00 0.000000000e+00 0.000000000e+00
 0.000000000e+00 0.000000000e+00 0.000000000e+00 0.000000000e+00 0.000000000e+00
``` 

With the first line being as it is, it produces the following error message

`(gdb) r
Starting program: /scratch/gpfs/mr1884/scratch_traverse/gkylmax/traverse-wham1x-kinetic-fromfile-ic/rt_twostream
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/glibc-hwcaps/power9/libthread_db-1.0.so".
Grid size = 16 in psi, 50 in Z, 20 in Vpar, 20 in mu
Creating app object ...
rt_twostream: zero/alloc.c:117: gkyl_aligned_free_: Assertion `ptr' failed.

Program received signal SIGABRT, Aborted.
0x00002000425696f8 in raise () from /lib64/glibc-hwcaps/power9/libc-2.28.so
Missing separate debuginfos, use: yum debuginfo-install glibc-2.28-236.el8_9.12.ppc64le hwloc-libs-2.2.0-3.el8.ppc64le libevent-2.1.8-5.el8.ppc64le libgcc-8.5.0-20.el8.ppc64le libstdc++-8.5.0-20.el8.ppc64le openssl-libs-1.1.1k-12.el8_9.ppc64le zlib-1.2.11-25.el8.ppc64le
(gdb) bt
#0  0x00002000425696f8 in raise () from /lib64/glibc-hwcaps/power9/libc-2.28.so
#1  0x0000200042543ff4 in abort () from /lib64/glibc-hwcaps/power9/libc-2.28.so
#2  0x000020004255d280 in __assert_fail_base () from /lib64/glibc-hwcaps/power9/libc-2.28.so
#3  0x000020004255d324 in __assert_fail () from /lib64/glibc-hwcaps/power9/libc-2.28.so
#4  0x000020000037fed4 in gkyl_aligned_free_ (file=<optimized out>, line=<optimized out>, func=<optimized out>,
    ptr=0x0) at zero/alloc.c:117
#5  gkyl_aligned_free_ (file=<optimized out>, line=<optimized out>, func=<optimized out>, ptr=0x0)
    at zero/alloc.c:114
#6  0x00002000002bec24 in g_array_free (ptr=<optimized out>) at zero/array.c:61
#7  array_free (ref=0x103b6bc8) at zero/array.c:61
#8  0x00002000002bf3b8 in gkyl_ref_count_dec (ref=<optimized out>) at zero/gkyl_ref_count.h:53
#9  gkyl_array_release (arr=<optimized out>) at zero/array.c:212
#10 0x00002000003058d4 in gkyl_efit_new (filepath=<optimized out>, rz_poly_order=<optimized out>,
    rz_basis_type=<optimized out>, flux_poly_order=<optimized out>, use_gpu=<optimized out>) at zero/efit.c:182
#11 0x0000200000331f10 in gkyl_mirror_geo_new (inp=0x10020350 <inp>) at zero/mirror_geo.c:71
#12 0x00002000002d9840 in gkyl_gk_geometry_mirror_new (geometry_inp=<optimized out>) at zero/gk_geometry_mirror.c:91
#13 0x00002000003a1c0c in gkyl_gyrokinetic_app_new (gk=0x7ffffff6c1b0) at apps/gyrokinetic.c:262
#14 0x0000000010002d68 in main (argc=<optimized out>, argv=<optimized out>) at rt_twostream.c:706`

it seems like this can easily be fixed by only reading the numbers on the right side of the first line. Use reverse indexing to find the first numbers. Or some kind of more advanced string search for the first line of the document. It's important for robustness to make sure that the file reading doesn't need any modifications and works with the standard files.

**Comment by manauref** [comment]
fixed in PR #820
